'use strict';
// Batch 1 - Science themes. Each pack: 12 three-level groups (T) + 4 two-level groups (D).
module.exports = ({ T, D }) => [

  { title: 'Physics Lab',
    three: [
      T('Mechanics', 'Motion', 'Forces', 'Gravity,Friction,Tension,Thrust', 'Velocity,Acceleration,Momentum', 'Lever,Pulley,Pendulum'),
      T('Electricity', 'Circuit', 'Circuit Parts', 'Resistor,Capacitor,Transistor,Diode', 'Battery,Switch,Wire', 'Voltage,Current,Resistance'),
      T('Optics', 'Optical Instruments', 'Lens Types', 'Convex,Concave,Bifocal,Contact Lens', 'Telescope,Microscope,Periscope', 'Reflection,Refraction,Spectrum'),
      T('Sound Science', 'Sound Properties', 'Wave Parts', 'Crest,Trough,Wavelength,Amplitude', 'Tone,Volume,Frequency', 'Echo,Sonar,Decibel'),
      T('Thermal Physics', 'Temperature Scales', 'Heat Transfer', 'Conduction,Convection,Radiation,Insulation', 'Celsius,Fahrenheit,Kelvin', 'Freezing Point,Boiling Point,Melting Point'),
      T('Magnetism', 'Magnets', 'Magnet Types', 'Bar Magnet,Horseshoe Magnet,Fridge Magnet,Electromagnet', 'Compass Needle,Magnetic Pole,Magnetic Field', 'Dynamo,Generator,Transformer'),
      T('Atoms', 'Atomic Structure', 'Particles', 'Proton,Neutron,Electron,Quark', 'Nucleus,Electron Shell,Isotope', 'Fission,Fusion,Radioactivity'),
      T('Energy', 'Energy Types', 'Stored Energy', 'Chemical Energy,Elastic Energy,Potential Energy,Gravitational Energy', 'Kinetic Energy,Heat Energy,Sound Energy', 'Joule,Watt,Efficiency'),
      T('Measurement', 'Units', 'Length Units', 'Metre,Inch,Mile,Kilometre', 'Kilogram,Pound,Ounce', 'Litre,Second,Degree'),
      T('Great Physicists', 'Nobel Pioneers', 'Relativity Era', 'Einstein,Bohr,Planck,Heisenberg', 'Marie Curie,Hawking,Feynman', 'Tesla,Faraday,Maxwell'),
      T('Simple Machines', 'Lifting Machines', 'Basic Machines', 'Doorstop,Screw,Ramp,Crowbar', 'Crane,Hoist,Winch', 'Gear Train,Cam,Coil Spring'),
      T('Fluids', 'Liquids and Gases', 'States of Matter', 'Solid,Liquid,Gas,Plasma', 'Pressure,Density,Buoyancy', 'Viscosity,Surface Tension,Vacuum'),
    ],
    two: [
      D('Quantum World', 'Quantum Ideas', 'Photon,Qubit,Wave Function,Superposition', 'Entanglement,Uncertainty,Tunnelling'),
      D('Nuclear Power', 'Reactor', 'Control Rod,Coolant,Reactor Core,Cooling Tower', 'Uranium,Plutonium,Radiation Suit'),
      D('Clean Energy', 'Renewable Power', 'Solar Panel,Wind Turbine,Hydropower,Geothermal', 'Biofuel,Tidal Power,Wave Energy'),
      D('Electronics', 'Gadget Insides', 'Microchip,Sensor,Circuit Board,LED', 'Solder,Multimeter,Breadboard'),
    ] },

  { title: 'Chemistry Class',
    three: [
      T('Chemistry', 'Elements', 'Noble Gases', 'Helium,Neon,Argon,Krypton', 'Hydrogen,Oxygen,Nitrogen', 'Carbon,Sulphur,Phosphorus'),
      T('Metals', 'Precious Metals', 'Coin Metals', 'Gold,Silver,Copper,Nickel', 'Platinum,Palladium,Rhodium', 'Tin,Zinc,Aluminium'),
      T('Compounds', 'Common Compounds', 'Household Chemicals', 'Table Salt,Baking Soda,Washing Soda,Vinegar', 'Water,Carbon Dioxide,Ammonia', 'Methane,Ethanol,Glucose'),
      T('Acids and Bases', 'pH Scale', 'Strong Acids', 'Sulphuric Acid,Hydrochloric Acid,Nitric Acid,Citric Acid', 'Acidic,Neutral,Alkaline', 'Litmus Paper,Indicator,Buffer'),
      T('Chemical Reactions', 'Reaction Types', 'Burning', 'Combustion,Oxidation,Rusting,Explosion', 'Neutralisation,Fermentation,Decomposition', 'Catalyst,Reactant,Product'),
      T('Lab Equipment', 'Lab Glassware', 'Flasks', 'Conical Flask,Round Flask,Volumetric Flask,Florence Flask', 'Beaker,Test Tube,Pipette', 'Bunsen Burner,Tripod,Clamp Stand'),
      T('Periodic Table', 'Element Families', 'Alkali Metals', 'Lithium,Sodium,Potassium,Caesium', 'Halogens,Transition Metals,Metalloids', 'Group,Period,Atomic Number'),
      T('Mixtures', 'Separating Mixtures', 'Separation Methods', 'Filtration,Distillation,Evaporation,Chromatography', 'Solution,Suspension,Alloy', 'Solvent,Solute,Sieve'),
      T('Organic Chemistry', 'Hydrocarbons', 'Fuels from Oil', 'Petrol,Diesel,Kerosene,Paraffin', 'Alkane,Alkene,Benzene', 'Polymer,Plastic,Nylon'),
      T('Lab Safety', 'Protective Gear', 'Eye Protection', 'Goggles,Face Shield,Visor,Eyewash', 'Lab Coat,Gloves,Apron', 'Fume Hood,Fire Blanket,Spill Kit'),
      T('Alchemy and History', 'Old Chemistry', 'Alchemist Goals', 'Philosopher Stone,Elixir of Life,Gold Making,Potion', 'Mendeleev,Lavoisier,Dalton', 'Phlogiston,Four Elements,Cauldron'),
      T('Gases and Air', 'Atmosphere', 'Air Ingredients', 'Oxygen Gas,Nitrogen Gas,Argon Gas,Carbon Dioxide Gas', 'Ozone,Smog,Water Vapour', 'Exhaust,Greenhouse Gas,Pollutant'),
    ],
    two: [
      D('Crystals', 'Crystal Shapes', 'Cube,Prism Crystal,Needle,Hexagon', 'Salt Crystal,Snowflake,Quartz'),
      D('Explosive Science', 'Fireworks Chemistry', 'Gunpowder,Sparkler,Rocket Flare,Fuse', 'Firecracker,Catherine Wheel,Roman Candle'),
      D('Soap and Cleaning', 'Cleaning Products', 'Washing Liquid,Soap Bar,Hand Wash,Bleach Cleaner', 'Foam,Lather,Suds'),
      D('Kitchen Chemistry', 'Baking Reactions', 'Yeast,Baking Powder,Egg White Foam,Caramelising', 'Browning,Rising,Curdling'),
    ] },

  { title: 'Biology Basics',
    three: [
      T('Biology', 'Cell Biology', 'Cell Parts', 'Nucleus Core,Membrane,Cytoplasm,Mitochondria', 'Chloroplast,Vacuole,Cell Wall', 'Tissue,Body Organ,Organism'),
      T('Genetics', 'Heredity', 'DNA Building Blocks', 'Adenine,Thymine,Guanine,Cytosine', 'Gene,Chromosome,Genome', 'Dominant,Recessive,Mutation'),
      T('Evolution', 'Natural Selection', 'Evolution Evidence', 'Fossil,Darwin,Finches,Adaptation', 'Survival,Extinction,Species', 'Ancestor,Common Descent,Variation'),
      T('Plant Science', 'Photosynthesis', 'Photosynthesis Inputs', 'Sunlight,Chlorophyll,Carbon Dioxide Intake,Water Uptake', 'Glucose Sugar,Oxygen Release,Stomata', 'Leaf,Stem,Root'),
      T('Ecosystems', 'Food Chain', 'Food Chain Roles', 'Producer,Consumer,Decomposer,Predator', 'Prey,Scavenger,Herbivore', 'Habitat,Niche,Biome'),
      T('Microbiology', 'Microbes', 'Germs', 'Virus,Bacterium,Amoeba,Parasite', 'Mould,Yeast Cell,Algae', 'Petri Dish,Culture,Microscope Slide'),
      T('Reproduction', 'Life Cycle', 'Life Stages', 'Embryo,Infant,Adolescent,Elder', 'Egg,Larva,Pupa', 'Pollination,Fertilisation,Germination'),
      T('Flowers', 'Flower Anatomy', 'Flower Parts', 'Petal,Sepal,Stamen,Pistil', 'Pollen,Nectar,Seed Pod', 'Bee Visit,Bloom,Bud'),
      T('Classification', 'Taxonomy Ranks', 'Biological Kingdoms', 'Animalia,Plantae,Fungi Kingdom,Protista', 'Phylum,Class,Order', 'Family Rank,Genus,Linnaeus'),
      T('Senses', 'Sense Organs', 'The Five Senses', 'Sight,Hearing,Smell,Taste', 'Touch,Balance,Pain Sense', 'Retina,Eardrum,Taste Bud'),
      T('Animal Behaviour', 'Survival Tricks', 'Camouflage Masters', 'Chameleon Colours,Stick Insect,Leaf Insect,Arctic Hare', 'Migration,Hibernation,Mimicry', 'Instinct,Territory,Pack Hunting'),
      T('Bones and Muscles', 'Skeleton', 'Main Bones', 'Skull,Spine,Rib,Pelvis', 'Femur,Humerus,Kneecap', 'Biceps,Tendon,Ligament'),
    ],
    two: [
      D('Marine Biology', 'Plankton World', 'Krill,Diatom,Copepod,Algae Bloom', 'Reef,Kelp Forest,Tide Pool'),
      D('Insects Up Close', 'Insect Body', 'Antenna,Thorax,Abdomen,Compound Eye', 'Exoskeleton,Wing Case,Stinger'),
      D('Botany Tools', 'Gardening Science', 'Seedling,Compost Heap,Fertiliser,Greenhouse Glass', 'Grafting,Pruning,Pot Plant'),
      D('Fossil Hunting', 'Fossil Finds', 'Ammonite,Trilobite,Amber,Footprint Cast', 'Excavation,Palaeontologist,Museum Skeleton'),
    ] },

  { title: 'Medicine & Health',
    three: [
      T('Hospital Life', 'Hospital Staff', 'Doctors', 'Anaesthetist,Paediatrician,Cardiologist,Dentist', 'Ward Sister,Midwife,Pharmacist', 'Receptionist,Porter,Radiographer'),
      T('Illnesses', 'Common Illnesses', 'Cold Symptoms', 'Sneeze,Cough,Sore Throat,Runny Nose', 'Flu,Measles,Chickenpox', 'Fever,Rash,Migraine'),
      T('Medicine Cabinet', 'Medication', 'Pain Relief', 'Aspirin,Paracetamol,Ibuprofen,Codeine', 'Antibiotic,Vaccine,Antihistamine', 'Plaster,Dressing,Ear Thermometer'),
      T('First Aid', 'Emergency Care', 'First Aid Kit', 'Gauze,Antiseptic,Tweezers,Safety Pin', 'Recovery Position,CPR,Heimlich', 'Blue Light,Siren,Rescue Blanket'),
      T('Dental Care', 'Teeth', 'Tooth Types', 'Incisor,Canine Tooth,Molar,Wisdom Tooth', 'Enamel,Cavity,Gum', 'Electric Toothbrush,Floss,Dentist Chair'),
      T('Disease Prevention', 'Public Health', 'Healthy Habits', 'Handwashing,Mask,Sanitiser,Social Distance', 'Quarantine,Immunity,Epidemic', 'Checkup,Screening,Clinic'),
      T('Mental Wellbeing', 'Mind Care', 'Moods', 'Joy,Sadness,Anxiety,Stress', 'Therapy,Meditation,Counselling', 'Sleep,Journalling,Mindfulness'),
      T('Medical Tests', 'Scans', 'Imaging', 'X-ray,MRI,CT Scan,Ultrasound Scan', 'Blood Test,Biopsy,Eye Test', 'Heart Monitor,Reflex Hammer,Blood Pressure Cuff'),
      T('Surgery', 'Operating Theatre', 'Surgical Tools', 'Scalpel,Forceps,Clamp,Suture', 'Anaesthetic,Mask Gown,Surgical Light', 'Transplant,Bypass,Implant'),
      T('Nutrition', 'Vitamins', 'Vitamin Letters', 'Vitamin A,Vitamin B,Vitamin C,Vitamin D', 'Calcium,Iron Mineral,Zinc Mineral', 'Healthy Fat,Fibre,Carbohydrate'),
      T('Eye Care', 'Vision', 'Eye Parts', 'Pupil,Iris,Cornea,Lens Eye', 'Short Sight,Long Sight,Colour Blind', 'Glasses,Optician,Eye Drops'),
      T('Old Remedies', 'Home Remedies', 'Herbal Cures', 'Chamomile,Echinacea,Ginger Root,Peppermint Tea', 'Honey Lemon,Steam Bowl,Hot Water Bottle', 'Leeches,Bloodletting,Snake Oil'),
    ],
    two: [
      D('Drug Store', 'Pharmacy Shelf', 'Cough Syrup,Lozenge,Nasal Spray,Eye Ointment', 'Prescription,Chemist,Pill Box'),
      D('Hearing and Ears', 'Ear Parts', 'Eardrum Skin,Cochlea,Earwax,Earlobe', 'Hearing Aid,Earplugs,Audiologist'),
      D('Baby Care', 'Newborn Needs', 'Nappy,Dummy,Baby Bottle,Cot', 'Rattle,Pram,Bedtime Story'),
      D('Fitness Check', 'Body Measures', 'Pulse,Height Chart,Weighing Scale,Body Temperature', 'Waist Size,Heart Rate,Calorie Count'),
    ] },

  { title: 'Deep Space',
    three: [
      T('Astronomy', 'Stars', 'Star Types', 'Red Giant,White Dwarf,Supernova,Neutron Star', 'Pole Star,Binary Star,Shooting Star', 'Constellation,Zodiac,Star Chart'),
      T('Rocket Science', 'Rockets', 'Rocket Stages', 'Booster,Fuel Tank,Nozzle,Payload', 'Launch Pad,Countdown,Lift-off', 'Mission Control,Flight Director,Ground Crew'),
      T('Moon Missions', 'Lunar Exploration', 'Moon Features', 'Crater,Lunar Sea,Highlands,Moon Dust', 'Apollo,Lunar Rover,Moon Landing', 'Eclipse,Full Moon,Crescent'),
      T('Mars Mission', 'Red Planet', 'Mars Rovers', 'Curiosity,Perseverance,Opportunity,Spirit', 'Olympus Mons,Valles Marineris,Phobos', 'Dust Storm,Red Soil,Polar Cap'),
      T('Space Station', 'Life in Orbit', 'Space Station Modules', 'Airlock,Cupola,Docking Port,Solar Array', 'Weightless,Space Food,Spacesuit', 'Spacewalk,Experiment,Crew Quarters'),
      T('Galaxies', 'Cosmic Structures', 'Galaxy Shapes', 'Spiral Galaxy,Elliptical Galaxy,Irregular Galaxy,Milky Way', 'Andromeda,Magellanic Cloud,Quasar', 'Dark Matter,Dark Energy,Redshift'),
      T('Gas Giants', 'Outer Planets', 'Saturn Features', 'Saturn Rings,Titan,Enceladus,Cassini Division', 'Jupiter,Great Red Spot,Europa', 'Uranus,Neptune,Pluto'),
      T('Telescopes', 'Observatory', 'Famous Telescopes', 'Hubble,James Webb,Kepler Telescope,Arecibo', 'Dome,Lens Cap,Eyepiece', 'Stargazing,Spotting Scope,Star Party'),
      T('Space Agencies', 'Space Programmes', 'Agencies', 'NASA,ESA,Roscosmos,ISRO', 'Gemini,Mercury Programme,Artemis', 'Sputnik,Voyager,Vostok'),
      T('Aliens and Sci-Fi', 'Life Beyond Earth', 'Alien Ideas', 'UFO,Flying Saucer,Little Green Men,Crop Circle', 'Exoplanet,Habitable Zone,Radio Signal', 'Warp Drive,Hyperspace,Time Machine'),
      T('Comets and Rocks', 'Space Debris', 'Rocks in Space', 'Asteroid,Meteor,Meteorite,Comet Tail', 'Asteroid Belt,Kuiper Belt,Oort Cloud', 'Impact Crater,Space Junk,Fireball'),
      T('Astronauts', 'Space Careers', 'Astronaut Gear', 'Helmet,Oxygen Tank,Moon Boots,Gloves Suit', 'Mission Specialist,Commander,Flight Engineer', 'Training,Centrifuge,Simulator'),
    ],
    two: [
      D('Black Holes', 'Cosmic Monsters', 'Singularity,Accretion Disc,Gravity Well,Spaghettification', 'Event Horizon Edge,Hawking Radiation,Wormhole Mouth'),
      D('The Sun', 'Solar Features', 'Sunspot,Solar Flare,Corona,Prominence', 'Sunrise,Sunset,Solar Wind'),
      D('Planet Facts', 'Planet Properties', 'Atmosphere Layer,Orbit Path,Day Length,Gravity Pull', 'Ring System,Moon Count,Surface Temperature'),
      D('Night Sky Sights', 'Sky Wonders', 'Aurora,Meteor Shower,Blood Moon,Milky Band', 'Northern Lights,Planet Parade,Comet Visit'),
    ] },

  { title: 'Mathematics',
    three: [
      T('Maths', 'Arithmetic', 'Four Operations', 'Addition,Subtraction,Multiplication,Division', 'Fraction,Decimal,Percentage', 'Ratio,Average,Estimate'),
      T('Geometry', 'Shapes', 'Triangles', 'Equilateral,Isosceles,Scalene,Right Angle Triangle', 'Square,Circle,Pentagon', 'Cube Shape,Sphere,Pyramid'),
      T('Algebra', 'Equations', 'Algebra Pieces', 'Variable,Coefficient,Constant,Expression', 'Equation,Formula,Inequality', 'Graph,Function,Slope'),
      T('Numbers', 'Number Types', 'Kinds of Number', 'Prime,Even,Odd,Square Number', 'Integer,Negative,Fraction Number', 'Zero,Infinity,Pi'),
      T('Statistics', 'Data', 'Averages', 'Mean,Median,Mode,Range', 'Bar Chart,Pie Chart,Histogram', 'Survey,Sample,Probability'),
      T('Measuring Shapes', 'Circle Facts', 'Circle Parts', 'Radius,Diameter,Circumference,Arc', 'Area,Perimeter,Capacity', 'Protractor,Tape Measure,Compass Drawing'),
      T('Angles', 'Angle Types', 'Basic Angles', 'Acute,Obtuse,Reflex,Right Angle', 'Parallel,Perpendicular,Intersecting', 'Vertex,Degrees Angle,Bisect'),
      T('Mathematicians', 'Famous Thinkers', 'Early Mathematicians', 'Pythagoras,Euclid,Archimedes,Fibonacci', 'Gauss,Euler,Ada Lovelace', 'Turing,Fermat,Descartes'),
      T('Logic and Puzzles', 'Brain Teasers', 'Puzzle Types', 'Sudoku,Riddle,Maze,Crossword Grid', 'Magic Square,Tower of Hanoi,Rubik Cube', 'Logic Gate,Proof,Theorem'),
      T('Money Maths', 'Everyday Maths', 'Shopping Sums', 'Change,Discount,Bill Slip,Budget Sum', 'Interest,Profit,Loss Sum', 'Tax,Tip,Invoice Total'),
      T('Measuring Time', 'Time Maths', 'Time Units', 'Second Hand,Minute,Hour,Decade', 'Century,Millennium,Fortnight', 'Stopwatch,Time Zone,Timetable Sum'),
      T('Patterns', 'Sequences', 'Famous Sequences', 'Fibonacci Spiral,Arithmetic Sequence,Geometric Sequence,Prime List', 'Tessellation,Symmetry,Fractal', 'Kaleidoscope,Mosaic Pattern,Spirograph'),
    ],
    two: [
      D('Maths Tools', 'Drawing Instruments', 'Set Square,Divider,Pencil Compass,Stencil', 'Pocket Calculator,Abacus,Slide Rule'),
      D('Big and Small', 'Number Words', 'Million,Billion,Trillion,Googol', 'Half,Quarter,Dozen'),
      D('Symbols', 'Maths Symbols', 'Plus Sign,Minus Sign,Equals Sign,Square Root', 'Percent Sign,Pi Symbol,Infinity Symbol'),
      D('Coding Maths', 'Binary World', 'Bit,Byte,Binary Code,Hexadecimal', 'Algorithm,Boolean,Modulo'),
    ] },

];
