'use strict';
// Batch 6 - Society themes: politics, law, business, education, careers, mind (6 packs).
module.exports = ({ T, D }) => [

  { title: 'Politics & Government',
    three: [
      T('Government', 'Government Branches', 'Government Bodies', 'Parliament,Congress,Senate,Cabinet', 'Prime Minister,President,Chancellor', 'Monarch,Governor,Lord Mayor'),
      T('Elections', 'Voting', 'Voting Steps', 'Ballot Paper,Polling Station,Ballot Box,Voter Card', 'Candidate,Manifesto,Campaign Trail', 'Exit Poll,Landslide,Recount'),
      T('Political Ideas', 'Ideologies', 'Systems', 'Democracy,Monarchy,Republic,Dictatorship', 'Capitalism,Socialism,Communism', 'Liberalism,Conservatism,Anarchy'),
      T('International Bodies', 'World Organisations', 'Organisations', 'United Nations,NATO,European Union,World Bank', 'Red Cross,WHO,UNESCO', 'Olympic Committee,FIFA,Interpol'),
      T('Council Work', 'Council Services', 'Council Departments', 'Planning Office,Housing Department,Waste Collection,Highways Team', 'Town Hall Clerk,Ward Councillor,Parish Meeting', 'Council Tax,Bylaw,Public Consultation'),
      T('Flags and Symbols', 'National Symbols', 'Flag Designs', 'Stars and Stripes,Union Jack,Maple Leaf,Rising Sun', 'National Anthem,National Coat of Arms,National Bird', 'Passport Stamp,Embassy,Border Post'),
      T('Diplomacy', 'Foreign Affairs', 'Diplomats', 'Ambassador,Envoy,Consul,Delegate', 'Treaty,Summit Meeting,Sanctions', 'Embassy Staff,Visa Office,Peace Talks'),
      T('Taxes and Budget', 'Public Money', 'Taxes', 'Income Tax,Sales Tax,Property Tax,Customs Duty', 'Budget Speech,National Debt,Treasury', 'Subsidy,Pension Fund,Benefit Payment'),
      T('Protest and Rights', 'Citizen Power', 'Citizen Actions', 'Petition,Strike Action,March,Boycott', 'Free Speech,Right to Vote,Freedom of Press', 'Referendum,Lobbying,Whistleblower'),
      T('Royal Family', 'Monarchy Life', 'Royal Items', 'Crown,Sceptre,Orb,Throne Chair', 'Prince,Princess,Duchess', 'Palace Balcony,Royal Wedding,Jubilee'),
      T('Ancient Politics', 'Old Governments', 'City Governments', 'Roman Senate,Athenian Assembly,Roman Republic,Tribe Council', 'Feudal Lord,Warlord,Chieftain', 'Dynasty,Regent,Tsar'),
      T('Political Media', 'Politics in the News', 'Political Coverage', 'Scandal Headline,Opinion Column,Cartoon Page,Leader Article', 'Spin Doctor,Press Secretary,Pundit Panel', 'Soundbite,Debate Night,Hustings'),
    ],
    two: [
      D('Civic Duties', 'Being a Citizen', 'Jury Service,Census Form,Paying Tax,Voting Day', 'Volunteering,Neighbourhood Watch,Recycling Pledge'),
      D('Capital Cities', 'World Capitals', 'London,Paris,Tokyo,Cairo', 'Canberra,Ottawa,Brasilia'),
      D('Constitutions', 'Founding Documents', 'Bill of Rights,Magna Carta Charter,Independence Paper,Constitution Text', 'Amendment,Preamble,Article One'),
      D('Political Parties', 'Party Politics', 'Party Leader,Rosette,Party Conference,Manifesto Launch', 'Whip,Backbencher,Opposition'),
    ] },

  { title: 'Law & Order',
    three: [
      T('Courtroom', 'Trial', 'Court Roles', 'Judge,Jury,Defendant,Barrister', 'Witness,Clerk,Bailiff', 'Gavel,Court Dock,Witness Box'),
      T('Policing', 'Police Force', 'Police Equipment', 'Handcuffs,Truncheon,Police Radio,Body Camera', 'Patrol Car,Siren Light,Police Dog', 'Detective,Constable,Sergeant'),
      T('Crimes', 'Types of Crime', 'Property Crimes', 'Burglary,Robbery,Shoplifting,Vandalism', 'Fraud,Forgery,Blackmail', 'Arson,Piracy Crime,Smuggling'),
      T('Investigation', 'Crime Scene', 'Evidence', 'Fingerprints,DNA Sample,Footprint,CCTV Footage', 'Crime Tape,Forensic Suit,Evidence Bag', 'Suspect,Witness Statement,Lineup'),
      T('Prison', 'Jail Life', 'Jail Features', 'Cell,Cell Block,Warden,Visiting Room', 'Parole,Sentence,Probation', 'Bail,Remand,Release Day'),
      T('Laws', 'Types of Law', 'Law Types', 'Criminal Law,Civil Law,Contract Law,Family Law', 'Constitution Law,Tax Law,Property Law', 'Statute,Precedent,Bylaw Rule'),
      T('Lawyers', 'Legal Work', 'Legal Documents', 'Contract,Will,Deed,Affidavit', 'Solicitor,Notary,Paralegal', 'Law Firm,Legal Fees,Brief'),
      T('Traffic Law', 'Road Rules', 'Driving Offences', 'Speeding,Drink Driving,Parking Ticket,Red Light Offence', 'Speed Camera,Breathalyser,Penalty Points', 'Driving Ban,Fine,Licence Check'),
      T('Emergency Response', 'Rescue Teams', 'Rescue Services', 'Fire Crew,Sea Rescue Crew,Mountain Rescue,Lifeboat Crew', 'Emergency Number,Dispatcher,Control Room', 'Hazard Light,Rescue Helicopter,Search Party'),
      T('Justice History', 'Old Punishments', 'Punishments Old', 'Old Stocks,Ducking Stool,Branding,Transportation', 'Hanging Judge,Highwayman,Bow Street Runners', 'Newgate,Tower Prison,Alcatraz'),
      T('Detective Work', 'Detectives', 'Detective Tools', 'Notepad,Magnifier,Trench Coat,Deerstalker Hat', 'Informant,Stakeout,Interrogation', 'Cold Case,Case File,Verdict'),
      T('Rules and Rights', 'Rules', 'Rules Everywhere', 'School Rules,House Rules,Game Rules,Code of Conduct', 'Referee Rule,Curfew,Dress Code', 'Terms of Use,Danger Sign,Notice Board'),
    ],
    two: [
      D('Spies', 'Secret Service', 'Spy,Code Name,Wiretap,Safe Drop', 'Informer,Agent Handler,Hidden Letterbox'),
      D('Cyber Crime', 'Online Crime', 'Scam Email,Identity Theft,Phishing Site,Ransom Note', 'Fake Profile,Stolen Password,Data Breach'),
      D('Security Guards', 'Guarding', 'Bouncer,Night Watchman,Security Camera Room,Door Staff', 'Alarm Panel,Guard Dog,Torch Patrol'),
      D('Courts of the World', 'Famous Courts', 'Old Bailey,Supreme Court,International Court,Small Claims Court', 'Magistrate,Barrister Wig,Court Sketch'),
    ] },

  { title: 'Business & Money',
    three: [
      T('Business', 'Company Structure', 'Company Roles', 'Chief Executive,Line Manager,Accountant,Salesperson', 'Shareholder,Investor,Board Director', 'Employee,Boss,Intern'),
      T('Banking', 'Bank Services', 'Bank Accounts', 'Current Account,Savings Account,Mortgage,Overdraft', 'Cash Machine,Debit Card,Cheque Book', 'Safe Deposit,Bank Statement,Interest Rate'),
      T('Stock Market', 'Investing', 'Investments', 'Company Share,Bond,Fund,Dividend', 'Bull Market,Bear Market,Crash', 'Broker,Trader,Ticker Tape'),
      T('Money', 'Currencies', 'World Currencies', 'Dollar,Euro,Pound Sterling,Yen', 'Rupee,Peso,Franc', 'Rouble,Krona,Rand'),
      T('Marketing', 'Selling', 'Sales Tools', 'Discount Code,Free Sample,Loyalty Card,Flash Sale', 'Brand Image,Market Research,Target Audience', 'Cold Call,Pitch Deck,Customer Review'),
      T('Starting a Business', 'Startups', 'Startup Steps', 'Business Plan,Funding Round,Prototype Launch,Office Lease', 'Founder,Co-founder,Venture Capital', 'Pivot,Exit Strategy,Billion Startup'),
      T('Shops and Retail', 'Retail Types', 'Retail Places', 'Hypermarket,Boutique,Department Store,Corner Shop', 'Market Stall Retail,Shopping Centre,Outlet Store', 'Shelf Stacker,Till,Stockroom'),
      T('Office Life', 'Meetings', 'Meeting Items', 'Agenda,Minutes,Whiteboard Marker,Conference Table', 'Presentation Slide,Pie Chart Slide,Handout', 'Coffee Break,Team Lunch,Water Cooler'),
      T('Economics', 'Economy', 'Economic Ideas', 'Supply,Demand,Inflation,Recession', 'GDP,Unemployment,Trade Deficit', 'Tariff,Monopoly Power,Free Market'),
      T('Trade and Import', 'Global Trade', 'Trade Items', 'Export,Import,Trade Container Ship,Shipping Freight', 'Customs Officer,Tariff Form,Trade Fair', 'Exchange Rate,Free Trade,Embargo'),
      T('Insurance', 'Protection Plans', 'Insurance Types', 'Car Insurance,Home Insurance,Travel Insurance,Life Insurance', 'Premium,Claim,Excess', 'Policy,Underwriter,Loss Adjuster'),
      T('Saving and Spending', 'Personal Finance', 'Money Habits', 'Piggy Bank,Budget Planner,Wallet,Purse', 'Coupon,Bargain,Receipt Roll', 'Pocket Money,Allowance,Loan Shark'),
    ],
    two: [
      D('Accounting', 'Bookkeeping', 'Ledger,Balance Sheet,Invoice,Audit', 'Profit Margin,Expense Claim,Tax Return'),
      D('Auction House', 'Auctions', 'Auction Gavel,Bidder,Lot Number,Reserve Price', 'Going Going Gone,Paddle,Sold Sign'),
      D('Business Giants', 'Famous Businesses', 'Apple Company,Search Engine Giant,Microsoft,Toyota Corp', 'Coca Cola,McDonalds,Disney Company'),
      D('Coins and Notes', 'Cash', 'Penny,Dime,Nickel Coin,Quarter Coin', 'Banknote,Coin Purse,Cash Float'),
    ] },

  { title: 'Learning & Education',
    three: [
      T('School Subjects', 'Core Subjects', 'Sciences at School', 'Physics Class,Chemistry Lesson,Biology Lesson,Science Fair', 'Maths Lesson,English Lesson,History Lesson', 'Geography Lesson,Art Lesson,Drama Lesson'),
      T('University', 'Higher Education', 'Degrees', 'Bachelor,Master,Doctorate,Diploma', 'Lecture Hall,Tutorial,Seminar', 'Freshers Week,Graduation Gown,Student Loan'),
      T('Exams', 'Testing', 'Exam Items', 'Question Paper,Answer Booklet,Invigilator,Calculator Allowed', 'Revision,Mock Exam,Past Paper', 'Grade,Pass Mark,Results Day'),
      T('School Calendar', 'Term Time', 'Term Events', 'Parents Evening,Nativity Play,Harvest Assembly,World Book Day', 'Half Term,Summer Holidays,Easter Break', 'Inset Day,Snow Day,Open Day'),
      T('School Staff', 'Teaching Roles', 'Staff Types', 'Headteacher,Teaching Assistant,Caretaker,Lunch Lady', 'Supply Teacher,Tutor,Lecturer', 'Professor,Dean,Librarian'),
      T('Study Materials', 'School Supplies', 'Stationery Kit', 'Pencil Tin,Sharpener Box,Glue Stick,Safety Scissors', 'Exercise Book,Worksheet Pad,Ring Binder', 'Lunchbox,PE Bag,School Bag'),
      T('Study Skills', 'Learning Styles', 'Study Methods', 'Flashcards,Mind Map,Highlighter,Revision Notes', 'Concentration,Memory Trick,Mnemonic', 'Study Group,Library Desk,Past Notes'),
      T('School Clubs', 'Club Activities', 'Club Games', 'Table Tennis Club,Chess Club,Drama Club,Choir Club', 'Debating Society,Eco Club,Coding Club', 'Club Badge,Club Night,Club Captain'),
      T('Field Studies', 'Outdoor Learning', 'Field Work', 'Pond Dipping,Bug Hunt,Rock Pooling,Leaf Rubbing', 'Nature Trail,Compass Walk,Orienteering', 'Field Notebook,Muddy Wellies,Wet Weather Plan'),
      T('Student Projects', 'Project Fair', 'Project Types', 'Volcano Model,Plant Experiment,Poster Board,Solar System Model', 'Lab Report,Hypothesis,Conclusion', 'Judges Panel,Ribbon,Trophy Table'),
      T('Skills and Talents', 'Abilities', 'Everyday Skills', 'Cooking Skill,Driving Skill,Swimming Skill,Typing Skill', 'Teamwork,Leadership,Problem Solving', 'Creativity,Patience,Inquisitiveness'),
      T('Learning Aids', 'Study Tools', 'Study Aids', 'Learning Flipchart,Learning Flash Drive,Educational App,Learning Game', 'Reading Glasses,Study Lamp,Bookstand', 'Tutor Notes,Online Lesson,Revision Guide'),
    ],
    two: [
      D('Nursery School', 'Early Years', 'Building Blocks,Play Dough,Finger Paint,Story Mat', 'Nap Time,Name Tag,Snack Break'),
      D('Language Lessons', 'Foreign Study', 'Phrasebook Lesson,Vocabulary List,Verb Table,Listening Test', 'Exchange Student,Pen Pal,Language Lab'),
      D('Graduation Day', 'Graduation', 'Cap and Gown,Mortarboard,Degree Scroll,Ceremony Hall', 'Photo Day,Speech Day,Alumni'),
      D('Scouts and Guides', 'Youth Groups', 'Badge,Woggle,Campfire Song,Knot Tying', 'Troop,Patrol,Jamboree'),
    ] },

  { title: 'Jobs & Careers',
    three: [
      T('Job Hunting', 'Job Hunt', 'Job Search Steps', 'CV,Cover Letter,Interview Invite,Reference', 'Job Advert,Recruiter,Application Form', 'Job Offer,Contract Signing,First Day'),
      T('Food Careers', 'Chefs and Food Jobs', 'Kitchen Staff', 'Head Chef,Sous Chef,Pastry Chef,Kitchen Porter', 'Waitress,Barista,Bartender', 'Sommelier,Meat Cutter,Baker'),
      T('Creative Jobs', 'Arts Careers', 'Creative Roles', 'Graphic Designer,Illustrator,Animator,Photographer', 'Author,Poet,Playwright', 'Sculptor,Potter,Muralist'),
      T('Outdoor Jobs', 'Nature Careers', 'Nature Workers', 'Farmer,Forester,Landscape Gardener,Gamekeeper', 'Park Ranger,Pool Attendant,Fisherman', 'Beekeeper,Shepherd,Lumberjack'),
      T('Transport Jobs', 'Travel Careers', 'Drivers', 'Bus Driver,Taxi Driver,Train Driver,Lorry Driver', 'Airline Pilot,Ship Captain,Air Steward', 'Cycle Courier,Mail Carrier,Delivery Rider'),
      T('Science Jobs', 'Research Careers', 'Scientists', 'Lab Chemist,Physicist,Biologist,Geologist', 'Astronomer,Meteorologist,Botanist', 'Zoologist,Archaeologist,Oceanographer'),
      T('Health Jobs', 'Care Careers', 'Care Workers', 'Carer,Physiotherapist,Eye Doctor,Vet', 'Chemist Shop Worker,Dietitian,Psychologist', 'Heart Surgeon,Radiology Nurse,Dental Nurse'),
      T('Money Jobs', 'Finance Careers', 'Finance Staff', 'Banker,Bank Teller,Auditor,Actuary', 'Economist,Stockbroker,Tax Adviser', 'Estate Agent,Auctioneer,Loan Officer'),
      T('Public Service Jobs', 'Civic Careers', 'Public Servants', 'Police Officer,Firefighter,Soldier,Border Officer', 'Court Judge,Solicitor Job,Detective Inspector', 'Politician,Diplomat,Civil Servant'),
      T('Tech Jobs', 'Digital Careers', 'Digital Roles', 'Software Engineer,Data Scientist,Web Developer,Systems Analyst', 'Cyber Expert,Games Tester,App Designer', 'Robotics Engineer,AI Researcher,Network Admin'),
      T('Teaching Jobs', 'Education Careers', 'Education Roles', 'Primary Teacher,Secondary Teacher,University Lecturer,Private Tutor', 'Life Coach,Mentor,Instructor', 'Examiner,Principal,Trainer'),
      T('Working Life', 'Workplace', 'Work Words', 'Salary,Wage,Bonus,Promotion', 'Holiday Pay,Sick Leave,Pension', 'Retirement,Redundancy,Resignation'),
    ],
    two: [
      D('Weekend Jobs', 'Part-time Work', 'Paper Round,Babysitting,Car Wash,Dog Walking', 'Pocket Money Job,Lemonade Stand,Odd Jobs'),
      D('Dream Jobs', 'Ambitions', 'Astronaut Dream,Footballer Dream,Pop Star Dream,Film Star Dream', 'Doctor Dream,Pilot Dream,Teacher Dream'),
      D('Skilled Workers', 'Skilled Trades', 'Pipe Fitter,Garage Mechanic,Key Cutter,Glazier Trade', 'Tiler Trade,Thatcher,Stonemason'),
      D('Workplace Safety', 'Safety at Work', 'Fire Drill,Safety Sign,First Aid Box,Risk Assessment', 'Fire Marshal,Assembly Point,Hard Hat Rule'),
    ] },

  { title: 'Mind & Emotions',
    three: [
      T('Emotions', 'Feelings', 'Basic Feelings', 'Happy,Angry,Scared,Surprised', 'Proud,Jealous,Lonely', 'Excited,Bored,Embarrassed'),
      T('Personality', 'Character Traits', 'Good Traits', 'Kind,Brave,Honest,Generous', 'Shy,Bossy,Stubborn', 'Cheerful,Grumpy,Clumsy'),
      T('Dreams and Sleep', 'Sleeping', 'Sleep Stages', 'Light Sleep,Deep Sleep,Dream Sleep,Insomnia', 'Snoring,Sleepwalking,Nightmare', 'Lucid Dream,Adult Nap,Bedtime Routine'),
      T('Memory', 'Remembering', 'Memory Types', 'Short-term Memory,Long-term Memory,Muscle Memory,Photographic Memory', 'Forgetfulness,Deja Vu,Amnesia', 'Mnemonic Device,Memory Palace,Diary'),
      T('Relationships', 'Friends and Family', 'Relationship Types', 'Best Friend,Pen Friend,Neighbour,Classmate', 'Sibling,Great Uncle,Grandparent', 'Partner,Stranger,Rival'),
      T('Behaviour', 'Habits', 'Good Habits', 'Brushing Teeth,Early Rising,Exercise Habit,Reading Habit', 'Nail Biting,Procrastination,Fidgeting', 'Politeness,Punctuality,Tidiness'),
      T('Thinking', 'Mind Skills', 'Thinking Skills', 'Reasoning,Imagination,Concentration Skill,Curiosity Skill', 'Decision,Opinion,Belief', 'Idea,Daydream,Wonder'),
      T('Psychology', 'Mind Science', 'Psychology Fields', 'Child Psychology,Sports Psychology,Educational Psychology,Social Psychology', 'Freud,Pavlov,Jung', 'Experiment Subject,Inkblot,Mind Map Study'),
      T('Fears', 'Phobias', 'Common Fears', 'Fear of Spiders,Fear of Heights,Fear of Dark,Fear of Crowds', 'Claustrophobia,Arachnophobia,Vertigo', 'Jump Scare,Scary Story,Haunted Ride'),
      T('Kindness', 'Good Deeds', 'Kind Acts', 'Sharing,Helping Hand,Thank You Note,Compliment', 'Donation,Volunteer Work,Charity Shop', 'Random Act,Hug,Smile'),
      T('Luck and Choice', 'Decisions and Chance', 'Chance Items', 'Coin Toss,Dice Roll,Spinner Wheel,Raffle', 'Palm Reading,Fortune Teller,Horoscope Sign', 'Crossroads Choice,Pros and Cons,Gut Feeling'),
      T('Sense of Humour', 'Humour', 'Funny Things', 'Joke,Funny Riddle,Prank,Tickle', 'Giggle,Chuckle,Belly Laugh', 'Funny Face,Clown Nose,Whoopee Cushion'),
    ],
    two: [
      D('Body Language', 'Non-verbal Clues', 'Eye Contact,Crossed Arms,Handshake,Posture', 'Facial Expression,Eyebrow Raise,Tone of Voice'),
      D('Success and Failure', 'Ups and Downs', 'Win,Lose,Draw,Tie', 'Trophy Moment,Setback,Comeback'),
      D('Growing Up', 'Age Stages', 'Toddler Tantrum,Teenage Years,Midlife,Golden Years', 'First Day Nerves,Birthday Wish,Wise Elder'),
      D('Self Care', 'Wellbeing Habits', 'Gratitude List,Digital Detox,Walk in Nature,Early Night', 'Hobby Time,Quiet Time,Stretching'),
    ] },

];
